# This workflow is used to build and test packages
# It is triggered by push, pull_request, or manual workflow_dispatch

name: Build and Test

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  define-packages:
    runs-on: ubuntu-latest
    # Skip all jobs if PR is in draft
    if: github.event.pull_request.draft == false

    outputs:
      packages: ${{ steps.packages.outputs.packages }}

    steps:
      - uses: actions/checkout@v4

      - name: Discover Packages
        id: packages
        # find all directories with an ato.yaml from the current directory and output the list as a json array
        run: |
          echo "packages=$(find . -name "ato.yaml" -exec dirname {} \; | jq -R -s -c 'split("\n")[:-1]')" >> "$GITHUB_OUTPUT"

  build:
    permissions:
      contents: read
      packages: read
    runs-on: ubuntu-latest
    needs: define-packages
    strategy:
      matrix:
        package: ${{ fromJSON(needs.define-packages.outputs.packages) }}
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      # FIXME: handle deps properly
      # ideally it'd determine if the package is in the same repo and, if so,
      # install via file instead
      - uses: atopile/setup-atopile@v1
        with:
          # ato-config: "packages/${{ matrix.package }}/ato.yaml"
          version: "4757b44281566f44710a5e251a18e1b66f4957da"

      - run: ato sync
        working-directory: ${{ matrix.package }}
      - run: ato build
        working-directory: ${{ matrix.package }}
