# This workflow is used to publish packages to the GitHub Package Registry
# It is manually triggered and only runs on the main branch

name: Publish Packages

on:
  workflow_dispatch:

jobs:
  define-packages:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    outputs:
      packages: ${{ steps.packages.outputs.packages }}

    steps:
      - uses: actions/checkout@v4

      - name: Discover Packages
        id: packages
        run: |
          echo "packages=$(find . -name "ato.yaml" -exec dirname {} \; | jq -R -s -c 'split("\n")[:-1]')" >> "$GITHUB_OUTPUT"

  build-and-publish:
    runs-on: ubuntu-latest
    needs: define-packages
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        package: ${{ fromJSON(needs.define-packages.outputs.packages) }}
      fail-fast: false

    permissions:
      id-token: write
      contents: read
      packages: read

    steps:
      - uses: actions/checkout@v4

      - uses: atopile/setup-atopile@v1
        with:
          working-directory: ${{ matrix.package }}

      - run: ato sync
        working-directory: ${{ matrix.package }}
      - run: ato build
        working-directory: ${{ matrix.package }}

      - uses: atopile/publish-package@v1
        with:
          package-entrypoint: ${{ matrix.package }}
          skip-duplicate-versions: true
          package-version: "" # Use the embedded version key
          ato-config: ${{ matrix.package }}/ato.yaml
